# Generated by Django 5.0.14 on 2026-02-27 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["name"],
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
            },
        ),
    ]
