# Generated by Django 5.0.14 on 2026-02-27 04:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="規則名稱")),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("max_consecutive_days", "最大連續工作天數"),
                            ("min_rest_hours", "最小休息時數"),
                            ("max_weekly_hours", "最大每週工時"),
                            ("mandatory_rest_day", "強制休息日"),
                        ],
                        max_length=50,
                        verbose_name="規則類型",
                    ),
                ),
                ("value", models.JSONField(verbose_name="規則值")),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_rules",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
            ],
            options={
                "verbose_name": "排班規則",
                "verbose_name_plural": "排班規則",
                "ordering": ["organization", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShiftTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="班別名稱")),
                ("start_time", models.TimeField(verbose_name="開始時間")),
                ("end_time", models.TimeField(verbose_name="結束時間")),
                (
                    "break_minutes",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="休息分鐘數",
                    ),
                ),
                (
                    "overlap_minutes",
                    models.IntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="交接重疊分鐘數",
                    ),
                ),
                (
                    "min_staff_count",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="最低人力配置",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_templates",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
                (
                    "required_certifications",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shift_templates",
                        to="employees.certification",
                        verbose_name="所需證照",
                    ),
                ),
            ],
            options={
                "verbose_name": "班別模板",
                "verbose_name_plural": "班別模板",
                "ordering": ["organization", "start_time"],
            },
        ),
    ]
