# Generated by Django 5.0.14 on 2026-02-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shifttemplate",
            name="break_minutes",
            field=models.PositiveIntegerField(default=0, verbose_name="休息分鐘數"),
        ),
        migrations.AlterField(
            model_name="shifttemplate",
            name="overlap_minutes",
            field=models.PositiveIntegerField(
                default=30, verbose_name="交接重疊分鐘數"
            ),
        ),
    ]
