# Generated by Django 5.0.14 on 2026-05-24 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("shifts", "0003_shiftemployeepriority"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_time_of_day",
                    models.CharField(
                        choices=[
                            ("any", "不限"),
                            ("morning", "早班"),
                            ("afternoon", "中班"),
                            ("evening", "晚班"),
                            ("night", "深夜"),
                        ],
                        default="any",
                        max_length=20,
                        verbose_name="時段範圍",
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("gender", "性別"),
                            ("height_cm", "身高（公分）"),
                            ("weight_kg", "體重（公斤）"),
                            ("age_years", "年齡（歲）"),
                            ("tag", "員工標籤"),
                            ("certification", "證照"),
                        ],
                        max_length=20,
                        verbose_name="條件類型",
                    ),
                ),
                (
                    "condition_operator",
                    models.CharField(
                        choices=[
                            ("eq", "等於"),
                            ("ne", "不等於"),
                            ("gte", "大於等於"),
                            ("lte", "小於等於"),
                            ("in", "屬於"),
                            ("contains", "包含"),
                        ],
                        max_length=10,
                        verbose_name="比較運算子",
                    ),
                ),
                (
                    "condition_value",
                    models.JSONField(
                        help_text='依 condition_type 而定：性別="male"、身高=175、tag=["driver"]、證照=[cert_id,...]',
                        verbose_name="條件值",
                    ),
                ),
                (
                    "quantifier",
                    models.CharField(
                        choices=[
                            ("at_least", "至少"),
                            ("at_most", "至多"),
                            ("exactly", "恰好"),
                        ],
                        default="at_least",
                        max_length=10,
                        verbose_name="數量規則",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="數量"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="前端 builder 自動生成，用於 audit log",
                        max_length=255,
                        verbose_name="人類可讀描述",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("hard", "硬約束"), ("soft", "軟約束")],
                        default="hard",
                        max_length=10,
                        verbose_name="約束強度",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_constraints",
                        to="organizations.branch",
                        verbose_name="適用分店（None = 全機構）",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_constraints",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
                (
                    "shift_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_constraints",
                        to="shifts.shifttemplate",
                        verbose_name="適用班別（None = 任何班別）",
                    ),
                ),
            ],
            options={
                "verbose_name": "團隊規則",
                "verbose_name_plural": "團隊規則",
                "ordering": ["organization", "shift_template", "condition_type"],
            },
        ),
    ]
