# Generated by Django 5.0.14 on 2026-08-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0004_teamconstraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftrule",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("max_consecutive_days", "最大連續工作天數"),
                    ("min_rest_hours", "最小休息時數"),
                    ("max_weekly_hours", "最大每週工時"),
                    ("mandatory_rest_day", "強制休息日"),
                    ("max_daily_hours", "每日最大工時"),
                ],
                max_length=50,
                verbose_name="規則類型",
            ),
        ),
    ]
