# Generated by Django 5.0.14 on 2026-08-26 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0003_employee_birth_date_employee_gender_and_more"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "特休"),
                            ("sick", "病假"),
                            ("personal", "事假"),
                            ("menstrual", "生理假"),
                            ("marriage", "婚假"),
                            ("bereavement", "喪假"),
                            ("maternity", "產假"),
                            ("paternity", "陪產假"),
                            ("official", "公假"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="假別",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="開始日期")),
                ("end_date", models.DateField(verbose_name="結束日期")),
                ("reason", models.TextField(blank=True, verbose_name="事由")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待審核"),
                            ("approved", "已核准"),
                            ("rejected", "已駁回"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="審核時間"
                    ),
                ),
                ("review_note", models.TextField(blank=True, verbose_name="審核備註")),
                (
                    "affected_schedule_ids",
                    models.JSONField(
                        blank=True, default=list, verbose_name="受影響班次"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申請人",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="employees.employee",
                        verbose_name="員工",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="審核人",
                    ),
                ),
            ],
            options={
                "verbose_name": "請假申請",
                "verbose_name_plural": "請假申請",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="leaves_leav_organiz_752496_idx",
                    ),
                    models.Index(
                        fields=["employee", "start_date", "end_date"],
                        name="leaves_leav_employe_1211e8_idx",
                    ),
                ],
            },
        ),
    ]
