# Generated by Django 5.0.14 on 2026-08-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="submission_source",
            field=models.CharField(
                choices=[
                    ("self", "本人申請"),
                    ("manager_proxy", "主管代登記"),
                    ("system", "系統"),
                ],
                default="self",
                max_length=20,
                verbose_name="送件來源",
            ),
        ),
    ]
