# Generated by Django 5.0.14 on 2026-09-01 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0002_leaverequest_submission_source"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgLeaveSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_minutes",
                    models.PositiveIntegerField(
                        default=480, verbose_name="一天等於幾分鐘"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_settings",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
            ],
            options={
                "verbose_name": "請假設定",
                "verbose_name_plural": "請假設定",
            },
        ),
        migrations.CreateModel(
            name="LeaveTypeQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "特休"),
                            ("sick", "病假"),
                            ("personal", "事假"),
                            ("menstrual", "生理假"),
                            ("marriage", "婚假"),
                            ("bereavement", "喪假"),
                            ("maternity", "產假"),
                            ("paternity", "陪產假"),
                            ("official", "公假"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="假別",
                    ),
                ),
                (
                    "annual_quota_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="年度額度（分鐘，null=不限）",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_type_quotas",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
            ],
            options={
                "verbose_name": "假別額度",
                "verbose_name_plural": "假別額度",
                "unique_together": {("organization", "leave_type")},
            },
        ),
    ]
