# Generated by Django 5.0.14 on 2026-09-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0003_orgleavesettings_leavetypequota"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="結束時間"),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="request_unit",
            field=models.CharField(
                choices=[("full_day", "全日"), ("time_range", "時段")],
                default="full_day",
                max_length=10,
                verbose_name="請假單位",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="開始時間"),
        ),
    ]
