# Generated by Django 5.0.14 on 2026-05-24 16:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("schedules", "0002_scheduleversion_derived_from"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_year", models.PositiveSmallIntegerField(verbose_name="年")),
                (
                    "period_month",
                    models.PositiveSmallIntegerField(verbose_name="月 (1-12)"),
                ),
                (
                    "total_tokens",
                    models.PositiveIntegerField(
                        default=0, verbose_name="累積 token 數"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "開放中"),
                            ("closed", "已結算"),
                            ("billed", "已開立帳單"),
                        ],
                        default="open",
                        max_length=10,
                        verbose_name="狀態",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_periods",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
            ],
            options={
                "verbose_name": "計費週期",
                "verbose_name_plural": "計費週期",
                "ordering": ["-period_year", "-period_month"],
            },
        ),
        migrations.CreateModel(
            name="BillingRateConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_mode",
                    models.CharField(
                        choices=[
                            ("generate", "全自動生成 B"),
                            ("fill_gaps", "AI 補齊"),
                            ("derive_legal", "派生 A"),
                        ],
                        max_length=20,
                        verbose_name="計費類型",
                    ),
                ),
                (
                    "tokens_per_call",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="每次 token 數",
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="生效時間"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備註")),
            ],
            options={
                "verbose_name": "計費費率",
                "verbose_name_plural": "計費費率",
                "ordering": ["billing_mode", "-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["billing_mode", "-effective_from"],
                        name="billing_bil_billing_89358b_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrgBillingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_cap_tokens",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="月度上限 (None = 不限)"
                    ),
                ),
                (
                    "alert_threshold_pct",
                    models.PositiveSmallIntegerField(
                        default=80,
                        help_text="達 cap 的此百分比時寄通知",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="通知門檻 (% of cap)",
                    ),
                ),
                (
                    "billing_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="帳單通知 email",
                    ),
                ),
                (
                    "is_billing_enabled",
                    models.BooleanField(
                        default=True, verbose_name="啟用計費 (False = AI 拒絕呼叫)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_settings",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
            ],
            options={
                "verbose_name": "機構計費設定",
                "verbose_name_plural": "機構計費設定",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("mock", "Mock (Phase 2)"),
                            ("stripe", "Stripe (Phase 3)"),
                        ],
                        default="mock",
                        max_length=20,
                        verbose_name="付款服務商",
                    ),
                ),
                (
                    "external_token",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="外部 token (Stripe payment_method id)",
                    ),
                ),
                (
                    "last_4",
                    models.CharField(
                        blank=True, default="", max_length=4, verbose_name="卡號末四碼"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="卡片品牌"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_method",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
            ],
            options={
                "verbose_name": "付款方式",
                "verbose_name_plural": "付款方式",
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_mode",
                    models.CharField(
                        choices=[
                            ("generate", "全自動生成 B"),
                            ("fill_gaps", "AI 補齊"),
                            ("derive_legal", "派生 A"),
                        ],
                        max_length=20,
                        verbose_name="計費類型",
                    ),
                ),
                (
                    "tokens_charged",
                    models.PositiveIntegerField(verbose_name="扱費 token 數"),
                ),
                (
                    "solver_status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("infeasible", "無解"),
                            ("error", "錯誤"),
                        ],
                        max_length=20,
                        verbose_name="求解狀態",
                    ),
                ),
                (
                    "request_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="period_start, period_end, employee count, etc.",
                        verbose_name="請求元資料",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "billing_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="billing.billingperiod",
                        verbose_name="所屬週期",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
                (
                    "schedule_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_records",
                        to="schedules.scheduleversion",
                        verbose_name="相關排班版本",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="觸發人",
                    ),
                ),
            ],
            options={
                "verbose_name": "用量紀錄",
                "verbose_name_plural": "用量紀錄",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="billingperiod",
            index=models.Index(
                fields=["organization", "period_year", "period_month"],
                name="billing_bil_organiz_5cd4f3_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="billingperiod",
            unique_together={("organization", "period_year", "period_month")},
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="billing_usa_organiz_bcc0ac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["billing_period"], name="billing_usa_billing_79e9a1_idx"
            ),
        ),
    ]
