# Generated by Django 5.0.14 on 2026-05-28 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_seed_default_rates"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "threshold_pct",
                    models.PositiveSmallIntegerField(verbose_name="觸發門檻 (%)"),
                ),
                (
                    "tokens_at_alert",
                    models.PositiveIntegerField(verbose_name="觸發時累積 token"),
                ),
                (
                    "recipient",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="通知對象"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="寄送時間"),
                ),
                (
                    "billing_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="billing.billingperiod",
                        verbose_name="所屬週期",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_alerts",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
            ],
            options={
                "verbose_name": "計費通知",
                "verbose_name_plural": "計費通知",
                "ordering": ["-sent_at"],
                "unique_together": {("billing_period", "threshold_pct")},
            },
        ),
    ]
