# Generated by Django 5.0.14 on 2026-02-27 04:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("employees", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OvertimeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overtime_date", models.DateField(verbose_name="加班日期")),
                (
                    "overtime_type",
                    models.CharField(
                        choices=[
                            ("regular", "平日延長工時"),
                            ("rest_day", "休息日"),
                            ("holiday", "國定假日"),
                            ("special_holiday", "特別休假"),
                        ],
                        max_length=20,
                        verbose_name="加班類型",
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="加班時數",
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.34"),
                        max_digits=4,
                        verbose_name="倍率",
                    ),
                ),
                (
                    "calculated_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="計算金額",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備註")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overtime_records",
                        to="attendance.attendance",
                        verbose_name="出勤紀錄",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overtime_records",
                        to="employees.employee",
                        verbose_name="員工",
                    ),
                ),
            ],
            options={
                "verbose_name": "加班紀錄",
                "verbose_name_plural": "加班紀錄",
                "ordering": ["-overtime_date", "employee"],
                "indexes": [
                    models.Index(
                        fields=["overtime_date", "employee"],
                        name="overtime_ov_overtim_501011_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OvertimeRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overtime_type",
                    models.CharField(
                        choices=[
                            ("regular", "平日延長工時"),
                            ("rest_day", "休息日"),
                            ("holiday", "國定假日"),
                            ("special_holiday", "特別休假"),
                        ],
                        max_length=20,
                        verbose_name="加班類型",
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.34"),
                        max_digits=4,
                        verbose_name="倍率",
                    ),
                ),
                (
                    "max_hours_per_day",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="每日最大時數",
                    ),
                ),
                (
                    "max_hours_per_month",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="每月最大時數",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overtime_rules",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
            ],
            options={
                "verbose_name": "加班規則",
                "verbose_name_plural": "加班規則",
                "ordering": ["organization", "overtime_type"],
                "unique_together": {("organization", "overtime_type")},
            },
        ),
    ]
