# Generated by Django 5.0.14 on 2026-02-27 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LaborLawRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="規則名稱")),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("max_weekly_hours", "每週最大工時"),
                            ("max_daily_hours", "每日最大工時"),
                            ("min_rest_hours", "最小休息時數"),
                            ("max_consecutive_days", "最大連續工作天數"),
                            ("mandatory_rest_day", "強制休息日"),
                            ("overtime_multiplier", "加班倍率"),
                        ],
                        max_length=50,
                        verbose_name="規則類型",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="數值",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "勞基法規則",
                "verbose_name_plural": "勞基法規則",
                "ordering": ["rule_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("schedule", "排班檢查"),
                            ("attendance", "出勤檢查"),
                            ("overtime", "加班檢查"),
                            ("weekly", "週度檢查"),
                            ("monthly", "月度檢查"),
                        ],
                        max_length=50,
                        verbose_name="檢查類型",
                    ),
                ),
                ("check_period_start", models.DateField(verbose_name="檢查期間開始")),
                ("check_period_end", models.DateField(verbose_name="檢查期間結束")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pass", "通過"),
                            ("warning", "警告"),
                            ("violation", "違規"),
                        ],
                        max_length=20,
                        verbose_name="檢查狀態",
                    ),
                ),
                ("violations", models.JSONField(default=list, verbose_name="違規項目")),
                ("warnings", models.JSONField(default=list, verbose_name="警告項目")),
                (
                    "checked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="檢查時間"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備註")),
                (
                    "checked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_checks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="檢查人",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_checks",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
            ],
            options={
                "verbose_name": "合規檢查",
                "verbose_name_plural": "合規檢查",
                "ordering": ["-checked_at"],
            },
        ),
    ]
