# Generated by Django 5.0.14 on 2026-09-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0003_holiday"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgcompliancesettings",
            name="weekly_closed_days",
            field=models.JSONField(
                blank=True, default=list, verbose_name="每週公休日（0=週一…6=週日）"
            ),
        ),
    ]
