# Generated by Django 5.0.14 on 2026-02-27 04:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField(verbose_name="工作日期")),
                (
                    "clock_in",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上班打卡時間"
                    ),
                ),
                (
                    "clock_out",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下班打卡時間"
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="實際工時",
                    ),
                ),
                (
                    "is_substitute",
                    models.BooleanField(default=False, verbose_name="是否代班"),
                ),
                (
                    "is_cross_branch",
                    models.BooleanField(default=False, verbose_name="是否跨店支援"),
                ),
                (
                    "anomaly_flag",
                    models.BooleanField(default=False, verbose_name="異常標記"),
                ),
                (
                    "anomaly_reason",
                    models.TextField(blank=True, verbose_name="異常原因"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備註")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cross_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cross_branch_attendances",
                        to="organizations.branch",
                        verbose_name="支援分店",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="employees.employee",
                        verbose_name="員工",
                    ),
                ),
                (
                    "substitute_for",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substitute_attendances",
                        to="employees.employee",
                        verbose_name="代班對象",
                    ),
                ),
            ],
            options={
                "verbose_name": "出勤紀錄",
                "verbose_name_plural": "出勤紀錄",
                "ordering": ["-work_date", "employee"],
            },
        ),
        migrations.CreateModel(
            name="AnomalyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("late", "遲到"),
                            ("early_leave", "早退"),
                            ("no_clock_in", "未打卡上班"),
                            ("no_clock_out", "未打卡下班"),
                            ("overtime", "超時工作"),
                            ("mismatch", "與排班不符"),
                        ],
                        max_length=20,
                        verbose_name="異常類型",
                    ),
                ),
                ("description", models.TextField(verbose_name="異常描述")),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        default="medium",
                        max_length=20,
                        verbose_name="嚴重程度",
                    ),
                ),
                ("resolved", models.BooleanField(default=False, verbose_name="已處理")),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="處理時間"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="處理備註"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_anomalies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="處理人",
                    ),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="attendance.attendance",
                        verbose_name="出勤紀錄",
                    ),
                ),
            ],
            options={
                "verbose_name": "異常紀錄",
                "verbose_name_plural": "異常紀錄",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["work_date", "employee"], name="attendance__work_da_027cb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["work_date", "anomaly_flag"],
                name="attendance__work_da_cf31cf_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("employee", "work_date")},
        ),
    ]
