# Generated by Django 5.0.14 on 2026-02-27 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "建立"),
                            ("update", "更新"),
                            ("delete", "刪除"),
                            ("approve", "簽核"),
                            ("reject", "拒絕"),
                            ("publish", "發布"),
                            ("cancel", "取消"),
                        ],
                        max_length=20,
                        verbose_name="操作類型",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="模型名稱"),
                ),
                ("record_id", models.PositiveIntegerField(verbose_name="記錄ID")),
                ("object_id", models.PositiveIntegerField(null=True)),
                (
                    "old_data",
                    models.JSONField(blank=True, null=True, verbose_name="舊資料"),
                ),
                (
                    "new_data",
                    models.JSONField(blank=True, null=True, verbose_name="新資料"),
                ),
                (
                    "changes",
                    models.JSONField(blank=True, null=True, verbose_name="變更內容"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 位址"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="時間戳記"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="內容類型",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "稽核日誌",
                "verbose_name_plural": "稽核日誌",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["model_name", "record_id"],
                        name="audit_audit_model_n_95032e_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_audit_user_id_e8be02_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="audit_audit_action_2a1328_idx",
                    ),
                ],
            },
        ),
    ]
