# Generated by Django 5.0.14 on 2026-02-27 04:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="證照名稱"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="證照代碼"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="是否必需"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "證照",
                "verbose_name_plural": "證照",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="員工編號"
                    ),
                ),
                ("position", models.CharField(max_length=100, verbose_name="職位")),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("full_time", "全職"),
                            ("part_time", "兼職"),
                            ("dispatch", "派遣"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="契約類型",
                    ),
                ),
                (
                    "agreed_hours_per_week",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("40.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("168.00")),
                        ],
                        verbose_name="約定每週工時",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="到職日期")),
                ("is_active", models.BooleanField(default=True, verbose_name="在職")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organizations.branch",
                        verbose_name="所屬分店",
                    ),
                ),
                (
                    "certifications",
                    models.ManyToManyField(
                        blank=True,
                        related_name="employees",
                        to="employees.certification",
                        verbose_name="持有證照",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者帳號",
                    ),
                ),
            ],
            options={
                "verbose_name": "員工",
                "verbose_name_plural": "員工",
                "ordering": ["employee_id"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("full_time", "全職"),
                            ("part_time", "兼職"),
                            ("dispatch", "派遣"),
                        ],
                        max_length=20,
                        verbose_name="契約類型",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="開始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="結束日期"),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="基本薪資",
                    ),
                ),
                (
                    "agreed_hours_per_week",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("40.00"),
                        max_digits=5,
                        verbose_name="約定每週工時",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備註")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="employees.employee",
                        verbose_name="員工",
                    ),
                ),
            ],
            options={
                "verbose_name": "勞動契約",
                "verbose_name_plural": "勞動契約",
                "ordering": ["-start_date"],
            },
        ),
    ]
