# Generated by Django 5.0.14 on 2026-05-24 12:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employeeavailability_employeetimeslot"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="用於推算年齡；OR-Tools 需引用時改取派生年齡",
                null=True,
                verbose_name="生日",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "男"),
                    ("female", "女"),
                    ("other", "其他"),
                    ("undisclosed", "不公開"),
                ],
                default="",
                max_length=20,
                verbose_name="性別",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="height_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("50.00")),
                    django.core.validators.MaxValueValidator(Decimal("250.00")),
                ],
                verbose_name="身高（公分）",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="shift_pattern_preference",
            field=models.CharField(
                choices=[
                    ("none", "無偏好"),
                    ("alternating", "花花班（早晚交錯）"),
                    ("consecutive", "連上放長假"),
                ],
                default="none",
                max_length=20,
                verbose_name="排班模式偏好",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("20.00")),
                    django.core.validators.MaxValueValidator(Decimal("400.00")),
                ],
                verbose_name="體重（公斤）",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeDataConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consented_at", models.DateTimeField(verbose_name="同意時間")),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="撤回時間（None = 仍有效）"
                    ),
                ),
                (
                    "consent_version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="同意書版本"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備註")),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_consent",
                        to="employees.employee",
                        verbose_name="員工",
                    ),
                ),
            ],
            options={
                "verbose_name": "員工個資同意",
                "verbose_name_plural": "員工個資同意",
            },
        ),
        migrations.CreateModel(
            name="EmployeeTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, verbose_name="標籤代碼")),
                ("label", models.CharField(max_length=100, verbose_name="顯示名稱")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_tags",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
            ],
            options={
                "verbose_name": "員工標籤",
                "verbose_name_plural": "員工標籤",
                "ordering": ["organization", "code"],
                "unique_together": {("organization", "code")},
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="employees",
                to="employees.employeetag",
                verbose_name="員工標籤",
            ),
        ),
    ]
