# Generated by Django 5.0.14 on 2026-02-27 04:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        ("organizations", "0001_initial"),
        ("shifts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule_date", models.DateField(verbose_name="排班日期")),
                (
                    "expected_hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="預計工時",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("assigned", "已指派"),
                            ("confirmed", "已確認"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備註")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="employees.employee",
                        verbose_name="員工",
                    ),
                ),
                (
                    "shift_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="shifts.shifttemplate",
                        verbose_name="班別",
                    ),
                ),
            ],
            options={
                "verbose_name": "排班",
                "verbose_name_plural": "排班",
                "ordering": ["schedule_date", "shift_template__start_time"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("substitute", "臨時代班"),
                            ("split", "拆班"),
                            ("transfer", "跨店支援"),
                            ("cancel", "取消"),
                            ("modify", "修改"),
                        ],
                        max_length=20,
                        verbose_name="異動類型",
                    ),
                ),
                ("reason", models.TextField(verbose_name="異動原因")),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="異動時間"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="核准時間"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="核准人",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="異動人",
                    ),
                ),
                (
                    "original_employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="original_schedule_changes",
                        to="employees.employee",
                        verbose_name="原員工",
                    ),
                ),
                (
                    "replacement_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacement_schedule_changes",
                        to="employees.employee",
                        verbose_name="代班員工",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="schedules.schedule",
                        verbose_name="原排班",
                    ),
                ),
            ],
            options={
                "verbose_name": "排班異動",
                "verbose_name_plural": "排班異動",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_label",
                    models.CharField(max_length=100, verbose_name="版本標籤"),
                ),
                (
                    "version_type",
                    models.CharField(
                        choices=[("legal", "法規版"), ("actual", "實際版")],
                        max_length=20,
                        verbose_name="版本類型",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="期間開始")),
                ("period_end", models.DateField(verbose_name="期間結束")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已發布"),
                            ("approved", "已簽核"),
                            ("archived", "已歸檔"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="簽核時間"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="簽核人",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_versions",
                        to="organizations.branch",
                        verbose_name="所屬分店",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="建立人",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_versions",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
            ],
            options={
                "verbose_name": "排班版本",
                "verbose_name_plural": "排班版本",
                "ordering": ["-period_start", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="schedule",
            name="schedule_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="schedules.scheduleversion",
                verbose_name="排班版本",
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["schedule_date", "employee"],
                name="schedules_s_schedul_c4993e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["schedule_version", "schedule_date"],
                name="schedules_s_schedul_45062b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together={
                ("schedule_version", "employee", "schedule_date", "shift_template")
            },
        ),
    ]
