# Generated by Django 5.0.14 on 2026-05-24 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleversion",
            name="derived_from",
            field=models.ForeignKey(
                blank=True,
                help_text="A 班表（legal）通常派生自 B 班表（actual）；保留歷史可重新派生",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_versions",
                to="schedules.scheduleversion",
                verbose_name="派生來源版本",
            ),
        ),
    ]
