# Generated by Django 5.0.14 on 2026-07-10 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_scheduleversion_derived_from"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={
                "ordering": ["schedule_date", "shift_template__start_time", "id"],
                "verbose_name": "排班",
                "verbose_name_plural": "排班",
            },
        ),
    ]
