# Generated by Django 5.0.14 on 2026-08-06 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_birth_date_employee_gender_and_more"),
        ("organizations", "0001_initial"),
        ("schedules", "0003_alter_schedule_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleCellAcknowledgment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule_date", models.DateField(verbose_name="排班日期")),
                (
                    "version_type",
                    models.CharField(
                        choices=[("legal", "法規版"), ("actual", "實際版")],
                        max_length=10,
                        verbose_name="版本類型",
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="內容雜湊"
                    ),
                ),
                ("involved", models.JSONField(verbose_name="認可當下的版本與班次快照")),
                (
                    "acknowledged_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="認可時間"),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cell_acknowledgments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="認可人",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cell_acknowledgments",
                        to="employees.employee",
                        verbose_name="員工",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cell_acknowledgments",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
            ],
            options={
                "verbose_name": "簽核總表差異認可",
                "verbose_name_plural": "簽核總表差異認可",
                "ordering": ["-acknowledged_at"],
                "unique_together": {
                    (
                        "organization",
                        "employee",
                        "schedule_date",
                        "version_type",
                        "content_hash",
                    )
                },
            },
        ),
    ]
