# Generated by Django 5.0.14 on 2026-08-06 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_birth_date_employee_gender_and_more"),
        ("organizations", "0001_initial"),
        ("schedules", "0004_schedulecellacknowledgment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleOverlapDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_type",
                    models.CharField(
                        choices=[("legal", "法規版"), ("actual", "實際版")],
                        max_length=10,
                        verbose_name="版本類型",
                    ),
                ),
                ("schedule_date", models.DateField(verbose_name="群組起始日期")),
                (
                    "conflict_key",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="衝突鍵"
                    ),
                ),
                ("schedule_ids", models.JSONField(verbose_name="群組班次 ID")),
                (
                    "decision",
                    models.CharField(
                        choices=[("select", "保留指定班次"), ("coexist", "允許並存")],
                        max_length=10,
                        verbose_name="裁決",
                    ),
                ),
                ("selected_schedule_ids", models.JSONField(verbose_name="保留班次 ID")),
                ("comment", models.TextField(blank=True, verbose_name="備註")),
                (
                    "decided_at",
                    models.DateTimeField(auto_now=True, verbose_name="裁決時間"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overlap_decisions",
                        to="organizations.branch",
                        verbose_name="員工分店",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overlap_decisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="裁決人",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overlap_decisions",
                        to="employees.employee",
                        verbose_name="員工",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overlap_decisions",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
            ],
            options={
                "verbose_name": "重疊裁決",
                "verbose_name_plural": "重疊裁決",
                "ordering": ["-decided_at"],
                "unique_together": {("organization", "conflict_key")},
            },
        ),
        migrations.DeleteModel(
            name="ScheduleCellAcknowledgment",
        ),
    ]
