# Generated by Django 5.0.14 on 2026-08-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0005_scheduleoverlapdecision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("assigned", "已指派"),
                    ("confirmed", "已確認"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                    ("leave", "請假"),
                ],
                default="draft",
                max_length=20,
                verbose_name="狀態",
            ),
        ),
    ]
