# Generated by Django 5.0.14 on 2026-02-27 04:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="機構名稱")),
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="機構代碼",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="電話"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "機構",
                "verbose_name_plural": "機構",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="分店名稱")),
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="分店代碼",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="電話"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="organizations.organization",
                        verbose_name="所屬機構",
                    ),
                ),
            ],
            options={
                "verbose_name": "分店",
                "verbose_name_plural": "分店",
                "ordering": ["organization", "name"],
                "unique_together": {("organization", "code")},
            },
        ),
    ]
